In [1]:
import pandas as pd

In [2]:
air = pd.read_csv('airquality.csv')

In [3]:
air.shape

(153, 7)

In [4]:
air.head()

   Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
0           1   41.0    190.0   7.4    67      5    1
1           2   36.0    118.0   8.0    72      5    2
2           3   12.0    149.0  12.6    74      5    3
3           4   18.0    313.0  11.5    62      5    4
4           5    NaN      NaN  14.3    56      5    5

In [5]:
air.count()

Unnamed: 0    153
Ozone         116
Solar.R       146
Wind          153
Temp          153
Month         153
Day           153
dtype: int64

In [6]:
air.isnull().sum()

Unnamed: 0     0
Ozone         37
Solar.R        7
Wind           0
Temp           0
Month          0
Day            0
dtype: int64

In [7]:
air.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Temp,Month,Day
count,153.000000,116.000000,146.000000,153.000000,153.000000,153.000000,153.000000
mean,77.000000,42.129310,185.931507,9.957516,77.882353,6.993464,15.803922
std,44.311398,32.987885,90.058422,3.523001,9.465270,1.416522,8.864520
min,1.000000,1.000000,7.000000,1.700000,56.000000,5.000000,1.000000
25%,39.000000,18.000000,115.750000,7.400000,72.000000,6.000000,8.000000
50%,77.000000,31.500000,205.000000,9.700000,79.000000,7.000000,16.000000
75%,115.000000,63.250000,258.750000,11.500000,85.000000,8.000000,23.000000
max,153.000000,168.000000,334.000000,20.700000,97.000000,9.000000,31.000000

In [8]:
air.info()

<class 'pandas.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  153 non-null    int64
 1   Ozone       116 non-null    float64
 2   Solar.R     146 non-null    float64
 3   Wind        153 non-null    float64
 4   Temp        153 non-null    int64
 5   Month       153 non-null    int64
 6   Day         153 non-null    int64
dtypes: float64(3), int64(4)
memory usage: 8.5 KB

In [9]:
A = air.dropna()

In [10]:
A.shape

(111, 7)

In [11]:
A = air.fillna(0)

In [12]:
A.shape

(153, 7)

In [13]:
A.head()

   Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
0           1   41.0    190.0   7.4    67      5    1
1           2   36.0    118.0   8.0    72      5    2
2           3   12.0    149.0  12.6    74      5    3
3           4   18.0    313.0  11.5    62      5    4
4           5    0.0      0.0  14.3    56      5    5

In [14]:
A = air.fillna(method='pad')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [15]:
A.head()

   Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
0           1   41.0    190.0   7.4    67      5    1
1           2   36.0    118.0   8.0    72      5    2
2           3   12.0    149.0  12.6    74      5    3
3           4   18.0    313.0  11.5    62      5    4
4           5    0.0      0.0  14.3    56      5    5

In [16]:
A = air.fillna(method='backfill')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [17]:
A.head()

   Unnamed: 0  Ozone  Solar.R  Wind  Temp  Month  Day
0           1   41.0    190.0   7.4    67      5    1
1           2   36.0    118.0   8.0    72      5    2
2           3   12.0    149.0  12.6    74      5    3
3           4   18.0    313.0  11.5    62      5    4
4           5    0.0      0.0  14.3    56      5    5

In [18]:
import numpy as np

In [20]:
A = air['Ozone'].replace(np.nan,air['Ozone'].mean())

In [21]:
A.head()

0    41.00000
1    36.00000
2    12.00000
3    18.00000
4    42.12931
Name: Ozone, dtype: float64

In [23]:
A = air['Ozone'].replace(np.nan,air['Ozone'].mean())

In [24]:
A.head()

0    41.00000
1    36.00000
2    12.00000
3    18.00000
4    42.12931
Name: Ozone, dtype: float64

In [26]:
A = air['Ozone'].replace(np.nan,air['Ozone'].median())

In [27]:
A.head()

0    41.0
1    36.0
2    12.0
3    18.0
4    31.5
Name: Ozone, dtype: float64

In [29]:
A = air['Ozone'].replace(np.nan,air['Ozone'].mode())

ValueError: Series.replace cannot use dict-value and non-None to_replace

In [30]:
A.head()

0    41.0
1    36.0
2    12.0
3    18.0
4    31.5
Name: Ozone, dtype: float64

In [31]:
from sklearn.impute import SimpleImputer

In [32]:
from sklearn.impute import SimpleImputer

In [33]:
from sklearn.impute import SimpleImputer

In [34]:
from sklearn.impute import SimpleImputer

In [35]:
from sklearn.impute import SimpleImputer

In [36]:
imp = SimpleImputer(missing_values=np.nan,strategy='mean')

In [37]:
A = imp.fit_transform(air)

In [38]:
A

array([[  1.,  41., 190., ...,  67.,   5.,   1.],
       [  2.,  36., 118., ...,  72.,   5.,   2.],
       [  3.,  12., 149., ...,  74.,   5.,   3.],
       ...,
       [151.,  14., 191., ...,  75.,   9.,  28.],
       [152.,  18., 131., ...,  76.,   9.,  29.],
       [153.,  20., 223., ...,  68.,   9.,  30.]], shape=(153, 7))

In [39]:
A = pd.DataFrame(A, columns=air.columns)

In [40]:
A.head()

   Unnamed: 0     Ozone     Solar.R  Wind  Temp  Month  Day
0         1.0  41.00000  190.000000   7.4  67.0    5.0  1.0
1         2.0  36.00000  118.000000   8.0  72.0    5.0  2.0
2         3.0  12.00000  149.000000  12.6  74.0    5.0  3.0
3         4.0  18.00000  313.000000  11.5  62.0    5.0  4.0
4         5.0  42.12931  185.931507  14.3  56.0    5.0  5.0

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
len(A)

153

In [43]:
train, test = train_test_split(A)

In [44]:
len(train)

114

In [45]:
len(test)

39

In [ ]:
train.head()

In [ ]:
train, test = train_test_split(A, test_size = 0.20)

In [ ]:
len(test)

In [ ]:
len(train)

In [ ]:
A.describe()

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
B = scaler.fit_transform(A)

In [ ]:
pd.DataFrame(B).describe()

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
B = scaler.fit_transform(A)

In [ ]:
pd.DataFrame(B).describe()

In [ ]:
B = pd.DataFrame(B).describe()

In [ ]:
from sklearn.preprocessing import Binarizer

In [ ]:
bin = Binarizer(threshold=0.5)

In [ ]:
B = bin.fit_transform(B)

In [ ]:
pd.DataFrame(B)

In [ ]:
data=pd.read_csv('student.csv')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
B = le.fit_transform(data['name'])

In [ ]:
B

In [ ]:
B = data[:]

In [ ]:
B['name'] = le.fit_transform(B['name'])

In [ ]:
B

In [ ]:
A

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
X=A['Ozone'].values

In [ ]:
X=X.reshape(-1,1)

In [ ]:
Y = A['Temp']

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X,Y)

In [ ]:
model.score(X,Y)*100

In [ ]:
model.predict([[128]])

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(X,Y)